name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # ë˜ëŠ” master ë“± ê¸°ë³¸ ë¸Œëœì¹˜ ì´ë¦„

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Replace Firebase Config ğŸ¤«
        uses: peter-evans/replace-text@v5
        with:
          file: index.html
          from: "'FIREBASE_CONFIG_PLACEHOLDER'"
          to: ${{ secrets.FIREBASE_CONFIG }}

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # ë°°í¬ìš© ë¸Œëœì¹˜
          folder: . # í˜„ì¬ í´ë”ë¥¼ ë°°í¬
